### ISSUE TITLE
Docker images can't contain capitals, but some git repositories do

### ISSUE THREAD

**Issue by scraperdragon** [scraperwiki/hanoverd#59]
e.g. MOT-app
Should probably coerce names into lowercase?

**Comment by pwaller** [comment]
:+1:

**Comment by scraperdragon** [comment]
Suspect that ensuring ParseHookbotDockerPullPubEndpoint 's first return value is lowercase may well be sufficient -- https://github.com/scraperwiki/hanoverd/blob/8c0c52981626f22d566e623d5c0baa35b6fb6adb/hookbot.go#L95

**Comment by pwaller** [comment]
SGTM
